[build-system]
requires = ["setuptools>=61.0",
"leidenalg",
"copy",
"importlib",
"itertools",
"math",
"statistics",
"sigfig",
"time",
"igraph",
"leidenalg",
"networkx",
"numpy",
"pandas",
"sklearn",
"matplotlib",
"seaborn",
"mplcyberpunk"
]
build-backend = "setuptools.build_meta"

[project]
name = "louvainvsleiden"
version = "0.0.1"
authors = [
  { name="Lewis Hart", email="cannon.complexity@gmail.com" },
]
description = "test louvain alg vs leiden alg"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/cannon-complexity/louvainvsleiden"
"Bug Tracker" = "https://github.com/cannon-complexity/louvainvsleiden/issues"